name: Acceptance Tests [Nightly]

on:
  schedule:
    - cron: '0 21 * * *'

env:
  TERRAFORM_VERSION: ${{ vars.TERRAFORM_VERSION }}
  TF_VAR_cluster_version: ${{ vars.CLUSTER_VERSION }}

jobs:
  nightly_acceptance_tests_kind:
    uses: ./.github/workflows/reusable_acceptance_tests_kind.yaml
    with:
      kindVersion: ${{ vars.KIND_VERSION }}
      terraformVersion: ${{ env.TERRAFORM_VERSION }}
  nightly_acceptance_tests_eks:
    needs: [nightly_acceptance_tests_kind]
    uses: ./.github/workflows/reusable_acceptance_tests_eks.yaml
    with:
      terraformVersion: ${{ env.TERRAFORM_VERSION }}
  nightly_acceptance_tests_gke:
    needs: [nightly_acceptance_tests_kind]
    uses: ./.github/workflows/reusable_acceptance_tests_gke.yaml
    with:
      terraformVersion: ${{ env.TERRAFORM_VERSION }}
