name: Acceptance Tests [EKS]

on:
  workflow_dispatch:
    inputs:
      region:
        description: The AWS region
        default: ca-central-1
      azSpan:
        description: The number of AZs to spread cluster nodes across
        default: 2
      clusterVersion:
        description: The EKS cluster version
        default: 1.27
      nodesPerAz:
        description: The number of cluster nodes in each AZ
        default: 1
      instanceType:
        description: The type of EC2 instance to use for cluster nodes
        default: m7g.large
      terraformVersion:
        description: 'Terraform version to set up'
        required: true
        default: '1.7.1'
        type: string

env:
  AWS_REGION: ${{ github.event.inputs.region || vars.AWS_REGION }}
  TERRAFORM_VERSION: ${{ github.event.inputs.terraformVersion || vars.TERRAFORM_VERSION }}
  TF_VAR_az_span: ${{ github.event.inputs.azSpan || vars.AWS_AZ_NUMBER }}
  TF_VAR_capacity_type: ${{ vars.AWS_CAPACITY_TYPE }}
  TF_VAR_cluster_version: ${{ github.event.inputs.clusterVersion || vars.CLUSTER_VERSION }}
  TF_VAR_nodes_per_az: ${{ github.event.inputs.nodesPerAz || vars.AWS_NODES_PER_AZ }}
  TF_VAR_instance_type: ${{ github.event.inputs.instanceType || vars.AWS_INSTANCE_TYPE }}

jobs:
  acceptance_tests_eks:
    runs-on: ubuntu-latest
    steps:
      - name: 'Install Terraform'
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false
      - name: 'Provision EKS Cluster'
        run: |
          echo "Provisioning EKS Cluster"
      - name: Run Acceptance Test Suite
        run: |
          echo "Running acceptance tests"
