name: Acceptance Tests [KinD]

on:
  pull_request:
    branches:
      - main
    paths:
      - 'kubernetes/*.go'
      - 'go.mod'
  workflow_dispatch:
    inputs:
      kindVersion:
        description: 'KinD version to set up'
        required: true
        default: '0.20.0'
        type: string
      terraformVersion:
        description: 'Terraform version to set up'
        required: true
        default: '1.7.1'
        type: string

# No Env variables here.

jobs:
  set_variables:
    uses: ./.github/workflows/reusable_variables.yaml
  acceptance_tests_kind:
    uses: ./.github/workflows/reusable_acceptance_tests_kind.yaml
    needs: [set_variables]
    with:
      kindVersion: ${{ inputs.kindVersion || needs.set_variables.outputs.kindVersion }}
      terraformVersion: ${{ inputs.terraformVersion || needs.set_variables.outputs.terraformVersion }}
