name: Acceptance Tests [EKS]

on:
  workflow_dispatch:
    inputs:
      region:
        description: The AWS region
      azSpan:
        description: The number of AZs to spread cluster nodes across
      clusterVersion:
        description: The EKS cluster version
      nodesPerAz:
        description: The number of cluster nodes in each AZ
      instanceType:
        description: The type of EC2 instance to use for cluster nodes
      terraformVersion:
        description: 'Terraform version to set up'
        required: true
        type: string

# No Env variables here.

jobs:
  acceptance_tests_eks:
    uses: ./.github/workflows/reusable_acceptance_tests_eks.yaml
    with:
      region: ${{ inputs.region || vars.AWS_REGION }}
      azSpan: ${{ inputs.azSpan || vars.AWS_AZ_NUMBER }}
      clusterVersion: ${{ inputs.clusterVersion || vars.CLUSTER_VERSION }}
      nodesPerAz: ${{ inputs.nodesPerAz || vars.AWS_NODES_PER_AZ }}
      instanceType: ${{ inputs.instanceType || vars.AWS_INSTANCE_TYPE }}
      terraformVersion: ${{ inputs.terraformVersion || vars.TERRAFORM_VERSION }}
