name: Nightly Set Up Clusters

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  set_up_kind:
    uses: ./.github/workflows/reusable-setup-kind.yaml
    needs: [set_variables]
    with:
      kind_version: ${{ vars.KIND_VERSION }}
  set_up_aks:
    uses: ./.github/workflows/reusable-setup-aks.yaml
    needs: [set_up_kind]
    with:
      kubernetes_version: ${{ vars.KUBERNETES_VERSION }}
  set_up_eks:
    uses: ./.github/workflows/reusable-setup-eks.yaml
    needs: [set_up_kind]
    with:
      kubernetes_version: ${{ vars.KUBERNETES_VERSION }}
