name: Nightly set up KinD

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  set_variables:
    runs-on: ubuntu-latest
    outputs:
      kind_version: ${{ vars.KIND_VERSION }}
      kubernetes_version: ${{ vars.KUBERNETES_VERSION }}
    steps:
      - name: Set variables
        run: |
          echo "Set variables"
  n_set_up_kind:
    uses: ./.github/workflows/reusable-setup-kind.yaml
    needs: [set_variables]
    with:
      kind_version: ${{ needs.set_variables.outputs.kind_version }}
  set_up_aks:
    uses: ./.github/workflows/reusable-setup-aks.yaml
    needs: [n_set_up_kind]
    with:
      kubernetes_version: ${{ needs.set_variables.outputs.kubernetes_version }}
  set_up_eks:
    uses: ./.github/workflows/reusable-setup-eks.yaml
    needs: [n_set_up_kind]
    with:
      kubernetes_version: ${{ needs.set_variables.outputs.kubernetes_version }}
