name: Reusable Set Up KinD Workflow

on:
  workflow_call:
    inputs:
      kind_version:
        description: 'KinD version to set up'
        required: true
        type: string
      kubernetes_version:
        description: 'Kubernetes version to run'
        required: true
        type: string

env:
  KIND_NODE_IMAGE: ${{ fromJSON(vars.KIND_NODE_IMAGE)[inputs.kubernetes_version] }}

jobs:
  reusable_set_up_kind:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Node image
        if: ${{ !contains(env.KIND_NODE_IMAGE, 'kindest/node') }}
        run:
          exit 1
      - name: Reusable set up KinD
        uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0
        with:
          wait: 2m
          version: v${{ inputs.kind_version }}
          node_image: ${{ env.KIND_NODE_IMAGE }}
