name: Reusable Set Up GKE Workflow

on:
  workflow_call:
    inputs:
      kubernetes_version:
        description: 'Kubernetes version to provision'
        required: true
        type: string

jobs:
  reusable_set_up_eks:
    runs-on: ubuntu-latest
    steps:
      - name: Reusable set up GKE
        run: |
          echo "Provision Kubernetes version ${{ inputs.kubernetes_version }}"
