name: Set Reusable Variables
on:
  workflow_call:
    outputs:
      kind_version:
        description: 'KinD version to set up'
        value: '0.20.0'
jobs:
  set_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Set reusable variables
        run: |
          echo "Set reusable variables"
