name: Reusable Set Up KinD Workflow

on:
  workflow_call:
    inputs:
      kind_version:
        description: 'KinD version to set up'
        required: true
        type: string
      kubernetes_version:
        description: 'Kubernetes version to run'
        required: true
        type: string

jobs:
  reusable_set_up_kind:
    runs-on: ubuntu-latest
    steps:
      - name: Set Node image
        env:
          KIND_NODE_IMAGES: ${{ fromJSON(vars.KIND_NODE_IMAGE)[inputs.kubernetes_version] }}
          KUBERNETES_VERSION: ${{ inputs.kubernetes_version }}
        run: |
          echo KIND_NODE_IMAGE=`echo $KIND_NODE_IMAGES | jq 'env.KUBERNETES_VERSION'`
      - name: Reusable set up KinD
        if: ${{ contains(env.KIND_NODE_IMAGE, 'kindest/node') }}
        uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0
        with:
          wait: 2m
          version: v${{ inputs.kind_version }}
          node_image: ${{ env.KIND_NODE_IMAGE }}
