name: Acceptance Tests [GKE]

on:
  workflow_call:
    inputs:
      region:
        description: The GKE region
        type: string
      zone:
        description: The GKE zone
        type: string
      clusterVersion:
        description: The GKE cluster version
        type: string
      nodeCount:
        description: The number of cluster nodes to provision
        type: number
      instanceType:
        description: The type of GKE instance to use for cluster nodes
        type: string
      terraformVersion:
        description: Terraform version
        type: string

env:
  GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
  GOOGLE_REGION: ${{ inputs.region }}
  GOOGLE_ZONE: ${{ inputs.zone }}
  USE_GKE_GCLOUD_AUTH_PLUGIN: True
  TERRAFORM_VERSION: ${{ inputs.terraformVersion }}
  TF_VAR_cluster_version: ${{ inputs.clusterVersion }}
  TF_VAR_node_count: ${{ inputs.nodeCount }}
  TF_VAR_instance_type: ${{ inputs.instanceType }}

jobs:
  reusable_acceptance_tests_gke:
    runs-on: ubuntu-latest
    steps:
      - name: 'Install Terraform'
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false
      - name: 'Provision GKE Cluster'
        run: |
          echo "Provisioning GKE Cluster"
      - name: Run Acceptance Test Suite
        run: |
          echo "Running acceptance tests"
