name: Set up KinD

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      kind_version:
        description: 'KinD version to set up'
        required: true
        default: '0.20.0'
        type: string

jobs:
  set_variables:
    runs-on: ubuntu-latest
    outputs:
      kind_version: ${{ inputs.kind_version || '0.20.0' }}
    steps:
      - name: Set variables
        run: |
          echo "Setting up variables"
  set_up_kind:
    uses: ./.github/workflows/reusable-setup-kind.yaml
    needs: [set_variables]
    with:
      kind_version: ${{ needs.set_variables.outputs.kind_version }}
