name: Set up KinD

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      kind_version:
        description: 'KinD version to set up'
        required: true
        default: '0.19.0'
        type: string

env:
  KIND_VERSION: ${{ inputs.kind_version || '0.20.0' }}

jobs:
  set_up_kind:
    runs-on: ubuntu-latest
    steps:
      - name: Set up KinD
        uses: .github/workflows/reusable-setup-kind.yaml
