name: Set Up KinD

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      kind_version:
        description: 'KinD version to set up'
        required: true
        default: '0.20.0'
        type: string
#      kubernetes_version:
#        description: 'Kubernetes version to install'
#        required: true
#        default: '1.28'
#        type: string

jobs:
  set_variables:
    uses: ./.github/workflows/reusable-variables.yaml
  set_up_kind:
    uses: ./.github/workflows/reusable-setup-kind.yaml
    needs: [set_variables]
    with:
      kind_version: ${{ inputs.kind_version || needs.set_variables.outputs.kind_version }}
 #     kubernetes_version: ${{ inputs.kubernetes_version }}
